<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);NET_2_0</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);NET_2_0</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Core.System.Windows.Forms"/>
	<!-- <PackageReference Include="System" /> -->
    <!-- <PackageReference Include="System.Windows.Browser" /> -->
    <!-- <PackageReference Include="System.Xml" /> -->
    <!-- <PackageReference Include="System.Core" /> -->
	
	 <!-- <ProjectReference type="Gac" localcopy="True" refto="System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" /> -->
    <!-- <ProjectReference type="Gac" localcopy="True" refto="System.Windows.Browser, Version=3.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" /> -->
    <!-- <ProjectReference type="Gac" localcopy="True" refto="System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" /> -->
    <!-- <ProjectReference type="Gac" localcopy="True" refto="System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" /> -->
 
 
  </ItemGroup>

</Project>
