<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>TaskDialog</RootNamespace>
    <AssemblyName>TaskDialog</AssemblyName>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\PSTaskDialog\PSTaskDialog\PSTaskDialog.csproj" />
  </ItemGroup>
</Project>